### ISSUE TITLE
Deployment targets inconsistency between Pod and SPM metafiles

### ISSUE THREAD

**Issue by kambala-decapitator** [jessesquires/Foil#18]
*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*
yes

## General Information

 - Project version:
 
1.1.0 / the latest state
 
 - Platform/OS version: 
 
doesn't matter
 
 - IDE version:
 
doesn't matter
 
 - Devices: 
 
doesn't matter
 
 - Any related GitHub issues:

## Describe the bug
*Clearly and concisely describe the bug.*
Podspec declares deployment targets as 12.0 / 10.13 while Package.swift says 13 / 10.15.

## Steps to reproduce
*Provide numbered steps to follow that reproduce the bug.*
No steps.

## Expected behavior
*Clearly and concisely describe what you expected to happen.*
Deployment targets are identical.

## Stack trace, compiler error, code snippets
*Paste the full output of any stack trace or compiler error.*
*Include a code snippet that reproduces the described behavior, if applicable*
https://github.com/jessesquires/Foil/blob/main/Foil.podspec#L17
https://github.com/jessesquires/Foil/blob/main/Package.swift#L23

## Screenshots
*If applicable, add screenshots, gifs, or videos to help explain your problem.*

## Additional context
*Add any other useful information about the problem here.*
- SPM doesn't support tvOS and watchOS (dunno if that's possible at all though)
- also make sure that deployment targets in Xcode projects are synced

**Comment by jessesquires** [comment]
Ah, great catch. 💯 

Thank you @kambala-decapitator ! 🙌🏼
