### ISSUE TITLE
[Suggestion] Succinct implicit initialization

### ISSUE THREAD

**Issue by pointum** [jessesquires/Foil#29]
I’d suggest using something like this:

    @WrappedDefault("flagEnabled") var flagEnabled = true

Instead of this:

    @WrappedDefault(keyName: "flagEnabled", defaultValue: true)
    var flagEnabled: Bool

I think it’s clear from the declaration that the assigned value is a default/initial compile-time value. And this avoids duplicating the type declaration (`true` and `Bool`).

The trick is to use `init(wrappedValue: T, _ keyName: String` instead of `init(keyName: String, defaultValue: T`.

I used SwiftyUserDefaults before, but when property wrappers got available I came up with my own simpler solution. I’ve recently read your [article](https://www.jessesquires.com/blog/2021/03/26/a-better-approach-to-writing-a-userdefaults-property-wrapper/) to make sure I did not miss any caveat.

Here’s basically what I’ve been doing:

    @propertyWrapper
    struct Default<T> {
        private let key: String
        private let suite: UserDefaults

        init(wrappedValue: T, _ key: String, suite: UserDefaults = .standard) {
            suite.register(defaults: [key: wrappedValue])
            self.key = key
            self.suite = suite
        }
        
        ...

**Comment by jessesquires** [comment]
Thanks for this @pointum ! 🙌🏼  I love this idea.

Sorry it took me so long to reply.
