### ISSUE TITLE
[Feature]: A demo for SwiftUI project

### ISSUE THREAD

**Issue by yujinqiu** [jessesquires/Foil#45]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

How to integrated Foil with SwiftUI project ? 

### Problem

I try to integrated Foil in my SwiftUI project. 

UI binding: 

```swift
struct GeneralSettings: View {
       @ObservedObject var settings: AppSettings =  AppSettings()
    
        var body: some View {
            Stepper(value: $settings.fontSize, in: 0 ... 42) {
                Text("**Size:**    \(settings.fontSize)")
            }
        }
}
```

```swift
class AppSettings: ObservableObject {

    @WrappedDefault(key: "fontSize")
    var fontSize: Int = 30
}

```

The problem is  we can't not define `@Published` here when we have @WrappedDefault, so Stepper UI fontSize value is not update. 

and My workaround  is 

```swift
class AppSettings: ObservableObject {
    private var cancellables = Set<AnyCancellable>()
    @Published var needUpdate: Bool = false

    @WrappedDefault(key: "fontSize")
    var fontSize: Int = 30

       init() {
        $fontSize
            .sink { _ in
                self.needUpdate.toggle()
            }
            .store(in: &cancellables)
        }
}

```

I'm not sure  if this is correct way to  integrated  Foil with SwiftUI. 

### Proposed Solution

N/A

### Alternatives Considered

N/A

**Comment by jessesquires** [comment]
Hey @yujinqiu 👋🏼 

I'm not entirely sure about this, I would need to experiment.

cc @basememara @JonnyBeeGod -- can either of you help here? 😊

**Comment by basememara** [comment]
Thx for the ping! I added a SwiftUI example in PR #48.

Since only one property wrapper can be implemented at a time, we have to lean on Combine to listen for changes in the `.onReceive(publisher:)` modifier:

```swift
@State var flagEnabled = false

VStack {
    ...
}
.onReceive(AppSettings.shared.$flagEnabled) {
    flagEnabled = $0
}
```

**Comment by yujinqiu** [comment]
that's neat, brilliant idea thanks.  feel free to close this comment when PR is merged. 
Thanks @basememara  @jessesquires  for your great work :-)

**Comment by jessesquires** [comment]
I'll review the PR soon! 😊
