### ISSUE TITLE
Drop CocoaPods support?

### ISSUE THREAD

**Issue by basememara** [jessesquires/Foil#8]
I hope I don't get shunned 😅, but curious on how many feel about dropping CocoaPods support and just go pure Swift Package? The minimum Xcode version to submit to the App Store is Xcode 12 which is well above the minimum required to use SPM so I don't think supporting legacy is an issue.

Not only will this be less maintenance, but also we could get rid of the `.xcodeproj` and use only `Package.swift` (but I suspect there's more reasons than CocoaPods the Xcode project is needed).

**Comment by jessesquires** [comment]
Thanks for bringing this up @basememara!

I think there is still a strong case to support CocoaPods -- it is not dead yet. 😊 In fact, every major iOS project I have worked on in the past few years still depends on it, especially for bigger teams at bigger companies.

As you point out: for development you are free to use the Swift Package and ignore the Xcode project, or vice versa.

There is nothing particular about this project that requires CocoaPods. Rather, we distribute the library via both CocoaPods and SPM. Users can choose what works best for their projects.

Currently, there are [significant barriers to entirely replacing CocoaPods with SwiftPM](https://www.jessesquires.com/blog/tags/swiftpm/) for most teams and most non-trivial projects. Until those are fixed, I'm committed to distributing libraries via both SPM and CocoaPods. 😄

**Comment by jessesquires** [comment]
We'll see in a few weeks at WWDC if SwiftPM improvements are coming soon. Let's revisit this then, if changes are announced. 😄

**Comment by basememara** [comment]
Thx for the links and writing those up. You're right there's still a bit of a gap to be filled that CocoaPods is covering. Even getting the lint scripts to run seems a bit of a challenge at the moment with SPM, or even a meta description is just completely absent. Sounds good to table this for another version or two.
